---

s3_config:
  - access_key: abc
    secret_key: as
    region: eu-central-1
    endpoint: https://my.rgw.endpoint:8080
    skipSSLverify: false
  - access_key: def
    secret_key: as
    region: eu-central-2
    endpoint: https://my.rgw.endpoint:8080
    skipSSLverify: false
  - access_key: ghi
    secret_key: as
    region: eu-central-3
    endpoint: https://my.rgw.endpoint:8080
    skipSSLverify: false

# For generating annotations when we start/stop testcases
# https://grafana.com/docs/http_api/annotations/#create-annotation
grafana_config:
  endpoint: http://grafana
  username: admin
  password: grafana

tests:
  - name: My first example test
    read_weight: 20
    existing_read_weight: 0
    write_weight: 80
    delete_weight: 0
    list_weight: 0
    objects:
      size_min: 5
      size_max: 100
      # distribution: constant, random, sequential
      size_distribution: random
      unit: KB
      number_min: 10
      number_max: 10
      # distribution: constant, random, sequential
      number_distribution: constant
    buckets:
      number_min: 1
      number_max: 10
      # distribution: constant, random, sequential
      number_distribution: constant
    multipart:
      write_mpu_enabled: true
      write_part_size: 5
      write_unit: MB
      write_concurrency: 5
      read_mpu_enabled: true
      read_part_size: 5
      read_unit: MB
      read_concurrency: 5
    # Name prefix for buckets and objects
    bucket_prefix: 1255gosbench-
    object_prefix: obj
    # End after a set amount of time
    # Runtime in time.Duration - do not forget the unit please
    # stop_with_runtime: 60s # Example with 60 seconds runtime
    stop_with_runtime:
    # End after a set amount of operations (per driver)
    stop_with_ops: 10
    # Number of s3 performance test servers to run in parallel
    drivers: 2
    # Set wheter drivers share the same buckets or not
    # If set to True - bucket names will have the driver # appended
    drivers_share_buckets: True
    # Number of requests processed in parallel by each driver
    workers: 3
    # Remove all generated buckets and its content after run
    clean_after: True

...
